Fix building documentation
Running docs/run-dev-server returned an exception:

```
Dead link: /docs/reference/trace-config-proto in /usr/local/google/home/ddiproietto/perfetto/docs/data-sources/android-game-intervention-list.md
/usr/local/google/home/ddiproietto/perfetto/infra/perfetto.dev/node_modules/marked/lib/marked.cjs:2729
    throw e;
    ^

Error: Dead link: /docs/reference/trace-config-proto in /usr/local/google/home/ddiproietto/perfetto/docs/data-sources/android-game-intervention-list.md
Please report this to https://github.com/markedjs/marked.
    at assertNoDeadLink (/usr/local/google/home/ddiproietto/perfetto/infra/perfetto.dev/src/markdown_render.js:59:11)
    at renderLink (/usr/local/google/home/ddiproietto/perfetto/infra/perfetto.dev/src/markdown_render.js:97:5)
    at Renderer.renderer.link (/usr/local/google/home/ddiproietto/perfetto/infra/perfetto.dev/src/markdown_render.js:177:35)
    at Parser.parseInline (/usr/local/google/home/ddiproietto/perfetto/infra/perfetto.dev/node_modules/marked/lib/marked.cjs:2559:29)
    at Parser.parse (/usr/local/google/home/ddiproietto/perfetto/infra/perfetto.dev/node_modules/marked/lib/marked.cjs:2484:49)
    at Function.parse (/usr/local/google/home/ddiproietto/perfetto/infra/perfetto.dev/node_modules/marked/lib/marked.cjs:2305:19)
    at Function.marked [as parse] (/usr/local/google/home/ddiproietto/perfetto/infra/perfetto.dev/node_modules/marked/lib/marked.cjs:2721:19)
    at render (/usr/local/google/home/ddiproietto/perfetto/infra/perfetto.dev/src/markdown_render.js:183:24)
    at main (/usr/local/google/home/ddiproietto/perfetto/infra/perfetto.dev/src/markdown_render.js:200:20)
    at Object.<anonymous> (/usr/local/google/home/ddiproietto/perfetto/infra/perfetto.dev/src/markdown_render.js:228:1)
/usr/local/google/home/ddiproietto/perfetto/tools/node /usr/local/google/home/ddiproietto/perfetto/infra/perfetto.dev/src/markdown_render.js -i /usr/local/google/home/ddiproietto/perfetto/docs/data-sources/android-game-intervention-list.md --odir /usr/local/google/home/ddiproietto/perfetto/out/perfetto.dev -o /usr/local/google/home/ddiproietto/perfetto/out/perfetto.dev/docs/data-sources/android-game-intervention-list -t /usr/local/google/home/ddiproietto/perfetto/infra/perfetto.dev/src/template_markdown.html failed with code 1

```

This commit fixes the problem. I suspect the docs in perfetto.dev/docs
wre out of date because of this.

Change-Id: I42b3c107263f81978c8c24ad87f00addeb8565f2