Fix windows build with clang-cl
This fixes the following warning:

  ```
  FAILED: obj/src/base/base.string_utils.obj
  ../../buildtools/win/clang/bin\clang-cl.exe /nologo /showIncludes /FC -D_CRT_NONSTDC_NO_WARNINGS -D_CRT_SECURE_NO_DEPRECATE -D_CRT_SECURE_NO_WARNINGS -D_SCL_SECURE_NO_DEPRECATE -DNOMINMAX -D_HAS_EXCEPTIONS=0 -DWIN32_LEAN_AND_MEAN -DNDEBUG -DPERFETTO_IMPLEMENTATION -I../.. -I../../src/profiling/memory/include -I../../include -Igen/build_config -Igen -fstrict-aliasing -Wformat -Wno-deprecated /bigobj /Gy /FS /utf-8 /Zc:__cplusplus /WX -fcolor-diagnostics /W2 /wd4244 /wd4267 -Wno-float-equal -Wno-unused-macros -Wno-old-style-cast -Weverything -Wno-c++98-compat-pedantic -Wno-c++98-compat -Wno-disabled-macro-expansion -Wno-documentation-unknown-command -Wno-gnu-include-next -Wno-gnu-statement-expression -Wno-gnu-zero-variadic-macro-arguments -Wno-padded -Wno-poison-system-directories -Wno-reserved-id-macro -Wno-reserved-identifier -Wno-shadow-uncaptured-local -Wno-unknown-sanitizers -Wno-unknown-warning-option -Wno-unsafe-buffer-usage /O2 /Zc:inline /GR- /std:c++17 /c ../../src/base/string_utils.cc /Foobj/src/base/base.string_utils.obj /Fd"obj/src/base/base_c.pdb"
  ../../src/base/string_utils.cc(28,10): error: non-portable path to file '<Windows.h>'; specified path differs in case from file name on disk [-Werror,-Wnonportable-system-include-path]
  #include <windows.h>
           ^~~~~~~~~~~
           <Windows.h>
  ../../src/base/string_utils.cc(225,39): error: result of comparison 'int' > 2147483647 is always false [-Werror,-Wtautological-type-limit-compare]
        static_cast<int>(source.size()) > std::numeric_limits<int>::max()) {
        ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~ ^ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
  ../../src/base/string_utils.cc(231,17): error: implicit conversion changes signedness: 'int' to 'size_type' (aka 'unsigned long long') [-Werror,-Wsign-conversion]
    output.assign(size, '\0');
           ~~~~~~ ^~~~
  ../../src/base/string_utils.cc(242,39): error: result of comparison 'int' > 2147483647 is always false [-Werror,-Wtautological-type-limit-compare]
        static_cast<int>(source.size()) > std::numeric_limits<int>::max()) {
        ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~ ^ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
  ../../src/base/string_utils.cc(247,17): error: implicit conversion changes signedness: 'int' to 'size_type' (aka 'unsigned long long') [-Werror,-Wsign-conversion]
    output.assign(size, L'\0');
           ~~~~~~ ^~~~
  5 errors generated.
  ```

Change-Id: Icf1ce8e0cdc692b186048f56e50b09a4e768c6d0